prefect:
  api_url: http://127.0.0.1:4200/api

clickhouse:
  host: localhost
  port: 8123
  database: default
  username: default
  secure: false
  connect_timeout: 10
  send_receive_timeout: 300

deploy:
  enabled_modules:
    - tushare_trade_cal
    - tushare_daily_basic
    - tushare_stk_week_month_adj
    - tushare_income
    - tushare_balancesheet
    - tushare_cashflow
    - tushare_fina_indicator
    - tushare_fina_mainbz
    - tushare_stock_basic
    - tushare_stk_rewards
    - tushare_dividend
    - tushare_stk_factor_pro
    - tushare_cyq_chips
    - tushare_cyq_perf
    - tushare_share_float

  pools:
    default-process-pool:
      type: process
      job_variables:
        env:
          TZ: Asia/Shanghai
          PYTHONPATH: /app
          DO_NOT_TRACK: "1"
          PREFECT_API_URL: "http://prefect-server:4200/api"
        working_dir: /app
        stream_output: true
